version: "3"

services:
    cucumber_chrome:
        build:
            context: ./
            dockerfile: Dockerfile-chrome
        environment: 
            - sakai_browser=chrome
        env_file:
            - config.env
        entrypoint: mvn clean verify
        

    cucumber_firefox:
        build:
            context: ./
            dockerfile: Dockerfile-firefox
        environment: 
            - sakai_browser=firefox
        env_file:
            - config.env
        entrypoint: mvn clean verify
